version = 1

[[annotations]]
path = ["src/lib/img/favicon.ico"]
precedence = "override"
SPDX-FileCopyrightText = "2026 Damien Vesper <ldamienvesper@gmail.com>"
SPDX-License-Identifier = "AGPL-3.0-only"

[[annotations]]
path = [
    ".github/**",
    ".gitattributes",
    "**/.gitignore",
    "nginx.conf",
    "systemd.service",
    "**/*.html",
    "**/*.json",
    "**/*.lock",
    "**/*.md",
    "**/*.svg",
    "**/*.yaml"
]
precedence = "override"
SPDX-FileCopyrightText = "none"
SPDX-License-Identifier = "CC0-1.0"
