version = 1

[[annotations]]
path = [
    ".github/**",
    ".gitattributes",
    "**/.gitignore",
    "**/*.conf",
    "**/*.html",
    "**/*.json",
    "**/*.lock",
    "**/*.md",
    "**/*.svg",
    "**/*.yaml"
]
precedence = "override"
SPDX-FileCopyrightText = "none"
SPDX-License-Identifier = "CC0-1.0"
