version = 1

[[annotations]]
path = [".github/**", ".gitattributes", "**/.gitignore", "**/*.example", "**/*.json", "**/*.lock", "**/*.yaml"]
precedence = "override"
SPDX-FileCopyrightText = "none"
SPDX-License-Identifier = "CC0-1.0"
