name: Build
on:
  push:
    branches:
      - master
    paths: &paths
      - "src/**"
      - "*.json"
      - "bun.lock"
      - ".github/workflows/build.yml"
  pull_request:
    paths: *paths
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    concurrency: ci-build-${{ github.ref }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install Packages
        run: bun ci

      - name: Build Project
        run: bun run build

      - name: Typecheck Project
        run: bun typecheck
